# Generated by Django 4.1.5 on 2023-03-02 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=200)),
                ('correro_electonico', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_telefono', models.CharField(max_length=10)),
                ('numero_colaborador', models.CharField(max_length=10)),
                ('profecion', models.CharField(max_length=50)),
                ('curp', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=15)),
                ('fecha_validacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.empresa')),
                ('perona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=200)),
                ('fecha_resolucion', models.DateField()),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabajador.solicitud')),
                ('tipo_tramite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabajador.tramite')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabajador.rol'),
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
