# Generated by Django 4.1.5 on 2023-03-12 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0004_rename_perona_solicitud_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='correro_electonico',
            field=models.CharField(max_length=200, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=40, verbose_name='Razon Social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Numero de telefono'),
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actanacimiento', models.FileField(blank=True, null=True, upload_to='actanacimiento/%Y/%m/%d', verbose_name='Acta de Nacimineto')),
                ('fotopersona', models.FileField(blank=True, null=True, upload_to='fotopersona/%Y/%m/%d', verbose_name='Foto Personal')),
                ('firma', models.FileField(blank=True, null=True, upload_to='firma/%Y/%m/%d', verbose_name='Foto firma')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trabajador.solicitud')),
            ],
        ),
    ]
