# Generated by Django 4.1.5 on 2023-03-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0005_solicitud_cargo_alter_empresa_correro_electonico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
