# Generated by Django 4.1.5 on 2023-03-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0006_persona_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencial',
            name='fotopersona',
            field=models.ImageField(blank=True, null=True, upload_to='fotopersona/%Y/%m/%d', verbose_name='Foto Personal'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
